### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by HegeBa** [pdfplum/pdfplum#17] opened 2023-10-13 12:57 UTC
**Generate PDFs with Firestore**
pdfplum/firestore-pdf-generator@0.14.1

Firebase Extension update fails.
I have not configured anything different than I used to before the update, and I have uninstalled and installed it again with only default settings, still getting the same error.

; RESOURCE_ERROR at /deployments/firebase-ext-firestore-pdf-generator/resources/executePdfGenerator: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"function","description":"Invalid JSON payload received. Unknown name \"availableMemoryMB\" at 'function': Cannot find field."}]}],"message":"Invalid JSON payload received. Unknown name \"availableMemoryMB\" at 'function': Cannot find field.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/pracek-69089/locations/europe-west2/functions","httpMethod":"POST"}}

**Comment by sassanh** [comment] 2023-10-13 18:08
Thanks for reporting this! Yes unfortunately version 0.14.1 is broken, version 0.14.2 is already released and is under review by Firebase team to be published publicly, it shouldn't take more than 24 hours. You can read the details [here](https://github.com/pdfplum/pdfplum/issues/14)

As a temporary workaround you can install the release candidate versions:
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Ffirestore-pdf-generator@0.14.2-rc.2
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Fhttp-pdf-generator@0.14.2-rc.2

**Comment by sassanh** [comment] 2023-10-13 18:10
Duplicate of https://github.com/pdfplum/pdfplum/issues/14

**Closed by sassanh** 2023-10-13 18:10 UTC
