### ISSUE TITLE
"Generate PDFs with Firestore" Running action 'load template' goes into error: No such object: progetto-natu.appspot.com/template

### ISSUE THREAD

**Issue by Antonio-Patarozzi-NatuESG** [pdfplum/pdfplum#31] opened 2024-03-29 10:07 UTC
### Description

"Generate PDFs with Firestore"
Release 0.17.1

We have installed the extension into firebase. 
Configured the template directory and output directory. The directories is present into bucket. in templae directory we have insert you demo.zip files anche create the corresponding etries / record into Collections 

When we write into the table and the extension start triggered goes into the above error

### Steps to reproduce the behavior

Install the extension,
create the template and output directories 
create the collection with entries that extension trigger from
The error occurs

### Logs

ext-firestore-pdf-generator-executePdfGenerator

gmrsri6p5oki
ApiError: No such object: progetto-natu.appspot.com/template
    at new ApiError (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:79:15)
    at Util.parseHttpRespMessage (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:181:41)
    at Util.handleResp (/workspace/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:155:76)
    at Duplexify.<anonymous> (/workspace/node_modules/@google-cloud/storage/build/src/file.js:1072:38)
    at Duplexify.emit (node:events:517:28)
    at Duplexify.emit (node:domain:552:15)
    at PassThrough.emit (node:events:517:28)
    at PassThrough.emit (node:domain:552:15)
    at onResponse (/workspace/node_modules/retry-request/index.js:234:19)
    at PassThrough.<anonymous> (/workspace/node_modules/retry-request/index.js:165:11) {
  code: 404,
  errors: [],
  response: <ref *1> PassThrough {
    _readableState: ReadableState {
      state: 325910,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      errored: null,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      readable: [Function: next],
      end: [Array],
      finish: [Array],
      close: [Array]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    statusCode: 404,
    statusMessage: 'Not Found',
    request: {
      agent: [Agent],
      headers: [Ob…[messaggio troncato a causa delle dimensioni]

**Comment by sassanh** [comment] 2024-03-29 10:29
You should rename `demo.zip` to `template` or `template.zip`, this is mentioned in "How this extension works" section
<img width="973" alt="Screenshot 2024-03-29 at 1 57 00 PM" src="https://github.com/pdfplum/pdfplum/assets/1270688/efe11c6f-212c-4ae7-ad1b-b1500c3f2b79">

**Comment by Antonio-Patarozzi-NatuESG** [comment] 2024-03-29 11:23
I have tried but the problem remain

Il giorno ven 29 mar 2024 alle ore 11:29 Sassan Haradji <
***@***.***> ha scritto:

**Comment by Antonio-Patarozzi-NatuESG** [comment] 2024-03-29 11:26
The problem seam that the extension doens't found the bucket directory
template

Il giorno ven 29 mar 2024 alle ore 12:23 Antonio Patarozzi <
***@***.***> ha scritto:

**Comment by sassanh** [comment] 2024-03-29 11:27
Is there error the same after you rename the file and upload it? If it is still saying "No such object: progetto-natu.appspot.com/template", can you confirm the file "progetto-natu.appspot.com/template" exists and is readable for the extension? Maybe it is something with the read permissions of your bucket.

**Comment by Antonio-Patarozzi-NatuESG** [comment] 2024-03-29 11:55
progetto-natu.appspot.com/template is the path of template. If ia change
the cionfiguration with  progetto-natu.appspot.com/template1 the error tell
me No cuch object  progetto-natu.appspot.com/template1. the directory
template exist. The extension when install get all permission that have
need.


Il giorno ven 29 mar 2024 alle ore 12:28 Sassan Haradji <
***@***.***> ha scritto:

**Comment by sassanh** [comment] 2024-03-29 12:44
> progetto-natu.appspot.com/template is the path of template. If ia change the cionfiguration with progetto-natu.appspot.com/template1 the error tell me No cuch object progetto-natu.appspot.com/template1.

Yes "progetto-natu.appspot.com/template" is the path of the template and the error is saying this file doesn't exist, that's why I asked you check the file actually exists there, cause this error means either the file is not there, or it is there but the read permissions are not provided, it has nothing to do with the permissions you gave to the extension in installation time. Buckets have security rules which define who can read/read which objects:
<img width="352" alt="Screenshot 2024-03-29 at 4 10 22 PM" src="https://github.com/pdfplum/pdfplum/assets/1270688/47237086-b6d9-4685-acbc-1d9b672f80f8">

I tried this on my side and it is working, to continue this conversation I need you to write in proper English without typos and providing evidence so that I can find out what's going on, like screenshot of the security rules, screenshot of the object in the bucket with its info box open, new logs after each iteration of conversation here with new suggestions tried, etc.

I close this issue until such information is provided.

**Closed by sassanh** 2024-03-29 12:44 UTC
Labels: bug

**Comment by patsoftware** [comment] 2024-03-30 11:45
I found what the problem was. 

The error showing "No such object: project-natu.appspot.com/template" is incorrect. 

The problem is not in the bucket template directory but in the document inserted in the collections. 

The "_pdfplum_config" property instead of being inserted as the main property was inserted as a sub-property of colors (See collection of your demo). 

Perhaps it would help if the extension if the extension also includes this check, on the existence of "_pdfplum_config" and gives a relevant message..

Thank you for your time

**Comment by sassanh** [comment] 2024-03-30 12:00
I assume you are the author of this issue. I'm glad you found the issue.
I'm not sure if I understand the improvement you are suggesting, `_pdfplum_config` is an optional field, The extension should work even if it is not provided at all.

> (See collection of your demo).

Are you referring the `demo.json` file? That file doesn't have a `_pdfplum_config` and it is not meant to be used in firestore version of the extension, it is for the http version.

**Comment by patsoftware** [comment] 2024-03-30 14:39
Do you remember this example, https://console.firebase.google.com/u/0/project/change-with-real-project/extensions/instances/firestore-pdf-generator?tab=usage? Into extension "firestore-pdf-generator" tab usage. Demo, demo.zip, is  refers to this. The error shown is incorrect, it should have shown that the problem was the lack of indication of the property in the record, if that property is missing it goes into error, incorrectly highlighting another problem. You don't need to answer. If you want to take the advice, it is explained above how the extension should behave in these cases. Happy Easter

**Comment by sassanh** [comment] 2024-03-30 14:46
This is a link to your project, I don't have access to open it.
If you send the complete logs, I will be able to investigate it, I will try to check it myself too.

**Comment by Antonio-Patarozzi-NatuESG** [comment] 2024-03-30 14:58
There's no need. 

To replicate it,  you simply create a document in the collection (collection that extension controls to create the pdf) with the property _pdfplum_config as a sub-property of another property. 
For us the problem is closed. We have shown you where the problem is and how to give a more relevant message, because the message you are now giving is incorrect and misleading. Happy Easter.
