### ISSUE TITLE
render pdf() error w/ no debugging info available

### ISSUE THREAD

**Issue by elvacijunior** [pdfplum/pdfplum#11] opened 2023-08-29 11:13 UTC
Hi!

I recently installed Firebase Extension to Create PDFs upon new Documents in a specific collection. I worked with my template using the 'invoice' as a starting point and also tried using the demo template and object provided. I'm using the new syntax with the **_pdfplum_config** key in the object, but I always end up with an 'error' inside the **render pdf()**.

The error is always in the 'render pdf()' function and it is always a timeout. I've tried changing the timeout default settings from 60 to 120 and nothing changed. I looked around and saw that PDF generation for multiple pages in Puppeteer takes no longer than 30 seconds, even with the 'slow' effect that people mention finding when using Puppeteer in Cloud Functions. I'm here because I need the PDF generation functionality inside a Firebase project and this project seems like the most fluid path to getting the results I'm looking for.

I've tried looking into the code and into Puppeteer itself and the biggest hint I got is about some problems in **headless-chromium** running inside Google Functions, but the extension is running it inside App Engine if I'm not mistaken. Am I missing something? 
The document creation always triggers the function correctly, but a PDF file is never generated.

Hope I reported it correctly! :D

![Screenshot 2023-08-29 at 08 03 58](https://github.com/pdfplum/pdfplum/assets/9379101/3c7f2cee-bfaa-4e0a-9ce4-3d27beac7dbe)

Here's the object I'm creating in Firestore (the one given at the 'How the extension works' page in Firebase)
<img width="847" alt="Screenshot 2023-08-29 at 10 54 20" src="https://github.com/pdfplum/pdfplum/assets/9379101/dcf442e6-b7c1-4c92-bff0-ba239e35dd4e">

**Comment by sassanh** [comment] 2023-08-30 04:38
Thanks for reporting this!

I just tried a new instance of the extension with the default values and it worked.

While installing the extension I noticed something new, in the last step of installation "Configure extension" there is a new section "Configure advanced parameters"
<img width="701" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/33fa9ebd-11a7-4769-9e17-9643c2269cff">
This section includes setting the memory of the cloud function, which I think may be overriding the parameter with the same name I provided for the function. I set the default value for function memory to 1GB but this new "advanced" parameter's default value is 256MB, it may be the cause of the error because when the memory is less than 512MB (and sometimes even with 512MB, depends on your template) the function times out.

You should be able to change its value for an installed extension instance and there is no need to install from scratch, please let me know how it goes. If it works for you then I will try to provide a new version of the extension based on this new changes and update the docs.

If it doesn't work for you even with setting this parameter to 1024, please provide me a complete reproduction steps.

**Comment by sassanh** [comment] 2023-08-30 13:47
Regarding the title of this issue, unfortunately it is not easy to provide debugging info when the runner kills the process after timeout. Maybe we can check the memory size in environment variables and write a warning that running the function with this amount of memory may cause a timeout but after the process is killed we can't write anything.

**Comment by sassanh** [comment] 2023-08-30 16:02
I'm glad it worked. let's keep this issue open until the default value of the advanced parameter is set to 1024mb.

> Is there any way I could save the generated PDFs to a folder inside the bucket?

You need to set `OUTPUT_STORAGE_BUCKET` (labeled "Output Firebase Storage bucket name") extension parameter for this purpose as well as the `outputFileName` embedded parameter, also make sure you have created the folder:
<img width="247" alt="Screenshot 2023-08-30 at 7 29 13 PM" src="https://github.com/pdfplum/pdfplum/assets/1270688/bfd5f00d-e1a6-4b89-9f8e-8e52990966ae">

For example:
`OUTPUT_STORAGE_BUCKET` set to "some-bucket"
`outputFileName` set to "some-folder/output.pdf"
"some-folder" is created in "some-bucket" in Firebase console.

Then the files will be created in "some-bucket/some-folder/output.pdf"

**Comment by sassanh** [comment] 2023-10-13 07:08
I think this issue is resolved in the latest rc:
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Ffirestore-pdf-generator@0.14.2-rc.2
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Fhttp-pdf-generator@0.14.2-rc.2

Relevant: https://stackoverflow.com/questions/77269318/to-set-a-minimum-default-value-for-the-memory-of-a-firebase-extension-function/77281443?noredirect=1#comment136244506_77281443

**Closed by sassanh** 2023-10-13 07:08 UTC
